apiVersion: v1
kind: Secret
metadata:
  name: devops-pipeline-secrets
  namespace: default
type: Opaque
stringData:
  JENKINS_USER: "admin"
  JENKINS_TOKEN: "11b0800c53f26fbdd399f2f85533c6e64b"
  APP_SECRET: "changeme123"
